### ISSUE TITLE
Tool tip shows up as "?"

### ISSUE THREAD

**Issue by pfitzgibbon** [MichaelRFox/fxToolTip.js#6]
Hey Dr Fox, nice to meet you through this virtual realm. I replaced Claire Summers on your past team. We are working to update the Confidence Curve which uses this tool tip you created, but it appears as a "?" right now. We have tried rolling back the version of fxToolTip to 1.4.0 (late 2019), but still just a "?" is appearing. The error that it is throwing is "Uncaught ReferenceError: targetWidth is not defined". Looked through a lot of the code, but nothing stood out at me as a possible bug related to this (targetHeight works, why not targetWidth?). Let me know if you have any insight into why this may be happening. 

Patrick Fitzgibbon

**Comment by MichaelRFox** [comment]
Neither *targetHeight* nor *targetWidth* are variables defined in fxTooltip.js. So I'm thinking that these are variables defined in your code, not the fxTooltip.js library. Difficult to address this further without reproducible code.

**Comment by pfitzgibbon** [comment]
I'll talk to team management, but I'm sure we cannot share the code here, we also do not know where the error stems from in the code, so we would not know what code to share out of the entire app. 
None of the code for the web app has been edited since you last edited or ran it, we simply ran the build shell commands and had it build missing the tool tip (and the summary stats, those no longer appear, but they were not there on the app version built last winter either). 
Just wanted to run these errors by you to see if you'd know anything off the top of your head. If we cannot repair the apps, we are going to move to a different visualization such as Tableau or Plotly Dash and archive them.
